# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: carrot-mapper
  labels:
    app: frontend
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: frontend
    spec:
      initContainers:
        - name: wait-for-api
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -f http://api-service:8000/health; do
                echo "Waiting for API..."
                sleep 5
              done
        - name: wait-for-airflow
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -f http://airflow-webserver-service:8080/health; do
                echo "Waiting for Airflow..."
                sleep 5
              done
      containers:
        - name: frontend
          image: ghcr.io/health-informatics-uon/carrot/frontend:3.1.0
          command: ["node", "server.js"]
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
