apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- if .Values.initContainers.waitForApi.enabled }}
        - name: wait-for-api
          image: {{ .Values.initContainers.waitForApi.image }}
          command:
            - sh
            - -c
            - |
              until curl -f {{ .Values.initContainers.waitForApi.serviceUrl }}; do
                echo "Waiting for API..."
                sleep 5
              done
        {{- end }}
        {{- if .Values.initContainers.waitForAirflow.enabled }}
        - name: wait-for-airflow
          image: {{ .Values.initContainers.waitForAirflow.image }}
          command:
            - sh
            - -c
            - |
              until curl -f {{ .Values.initContainers.waitForAirflow.serviceUrl }}; do
                echo "Waiting for Airflow..."
                sleep 5
              done
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- range .Values.command }}
            - {{ . }}
            {{- end }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "frontend.fullname" . }}-config
            - secretRef:
                name: {{ include "frontend.fullname" . }}-secrets
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      