namespace: carrot-mapper-k8s

replicaCount: 1

image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  tag: "latest"
  args:
    - server
    - /data
    - --console-address
    - :9001

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /minio/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /minio/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

auth:
  rootUser: "minioadmin"
  rootPassword: "minioadmin"

# MinIO Browser Configuration
browser:
  enabled: "on"

# MinIO Domain
domain: "minio.carrot-mapper-k8s.svc.cluster.local"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: standard
  pvcName: minio-pvc

volumeMounts:
  name: data
  mountPath: /data
