image:
  repository: ghcr.io/health-informatics-uon/carrot/backend
  pullPolicy: IfNotPresent
  tag: "3.2.0"

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000
  name: api

ingress:
  enabled: false

# Resource limits and requests
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

# TODO: setup autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Environment variables for the api service
config:
  DB_ENGINE: "django.db.backends.postgresql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  STORAGE_TYPE: "minio"
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  FRONTEND_URL: "http://frontend-service:3000"
  DEBUG: "True"
  WORKER_SERVICE_TYPE: "airflow"
  AIRFLOW_BASE_URL: "http://airflow-webserver-service:8080/api/v1/"
  AIRFLOW_AUTO_MAPPING_DAG_ID: "auto_mapping"
  AIRFLOW_SCAN_REPORT_PROCESSING_DAG_ID: "scan_report_processing"
  AIRFLOW_RULES_EXPORT_DAG_ID: "rules_export"
  AIRFLOW_ADMIN_USERNAME: "admin"
  DATA_UPLOAD_MAX_MEMORY_SIZE: "10485760"
  SUPERUSER_DEFAULT_EMAIL: "admin@carrot.com"
  SUPERUSER_DEFAULT_USERNAME: "admin"

# Secret environment variables
secrets:
  DB_PASSWORD: "postgres"
  SECRET_KEY: "secret"
  SIGNING_KEY: "secret"
  MINIO_SECRET_KEY: "minioadmin"
  AIRFLOW_ADMIN_PASSWORD: "admin"
  SUPERUSER_DEFAULT_PASSWORD: "admin"
