apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: {{ .Values.service.portName }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
