# Airflow Scheduler Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.scheduler.name }}
  labels:
    component: airflow
    app: airflow-scheduler

spec:
  {{- if .Values.scheduler.autoscaling.enabled }}
  replicas: {{ .Values.scheduler.autoscaling.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
        component: airflow
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:14
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U {{ .Values.config.AIRFLOW_POSTGRES_USER }}; do
                echo "Waiting for postgres..."
                sleep 2
              done
        - name: wait-for-minio
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -f http://minio-service:9000/minio/health/live; do
                echo "Waiting for minio..."
                sleep 2
              done
        - name: wait-for-api
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -f http://api-service:8000/health; do
                echo "Waiting for API..."
                sleep 5
              done
      containers:
        - name: airflow-scheduler
          image: {{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}
          env:
            - name: AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER
              value: "{{ .Values.scheduler.env.AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER }}"
            - name: AIRFLOW_DEBUG_MODE
              value: "{{ .Values.scheduler.env.AIRFLOW_DEBUG_MODE }}"
          envFrom:
            - configMapRef:
                name: {{ include "airflow.fullname" . }}-config
            - secretRef:
                name: {{ include "airflow.fullname" . }}-secrets
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
