image:
  tag: ""

# Job configuration
job:
  restartPolicy: OnFailure
  activeDeadlineSeconds: 3600 # 1 hour
  backoffLimit: 3

# Dependencies on other services
dependencies:
  postgres:
    user: postgres
    password: postgres
    name: postgres

# OMOP Lite application configuration
config:
  schemaName: "omop"
  dataDir: "vocabs"
  synthetic: "true"

# Resource allocation
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Volume configuration for vocabulary files
volumes:
  enabled: false # Set to true if volumes are enabled

# Volume mounts configuration
volumeMounts:
  enabled: false # Set to true if volumes are enabled

