namespace: carrot-mapper-k8s

replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "14"

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 5432
  clusterIP: None
  portName: postgres
  serviceName: postgres-service

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

livenessProbe:
  exec:
    command:
      - pg_isready
      - -U
      - postgres
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - pg_isready
      - -U
      - postgres
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumeMounts:
  name: postgres-storage
  mountPath: /var/lib/postgresql/data

auth:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "postgres"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: standard
  pvcName: postgres-pvc
