apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MINIO_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }} 