apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}
      name: console
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: api
