apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
    component: backend
    service-type: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
    component: backend
