# ConfigMap for api configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: carrot-mapper
data:
  DB_ENGINE: "django.db.backends.postgresql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  STORAGE_TYPE: "minio"
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  FRONTEND_URL: "http://frontend-service:3000"
  DEBUG: "True"
  WORKER_SERVICE_TYPE: "airflow"
  AIRFLOW_BASE_URL: "http://airflow-webserver-service:8080/api/v1/"
  AIRFLOW_AUTO_MAPPING_DAG_ID: "auto_mapping"
  AIRFLOW_SCAN_REPORT_PROCESSING_DAG_ID: "scan_report_processing"
  AIRFLOW_RULES_EXPORT_DAG_ID: "rules_export"
  AIRFLOW_ADMIN_USERNAME: "admin"
  DATA_UPLOAD_MAX_MEMORY_SIZE: "10485760"
  SUPERUSER_DEFAULT_EMAIL: "admin@carrot.com"
  SUPERUSER_DEFAULT_USERNAME: "admin"

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: carrot-mapper
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  SECRET_KEY: "secret"
  SIGNING_KEY: "secret"
  MINIO_SECRET_KEY: "minioadmin"
  AIRFLOW_ADMIN_PASSWORD: "admin"
  SUPERUSER_DEFAULT_PASSWORD: "admin"
