apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
    component: frontend
spec:
  {{- if .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
        component: frontend
    spec:
      initContainers:
        - name: wait-for-api
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -f http://api-service:8000/health; do
                echo "Waiting for API..."
                sleep 5
              done
        - name: wait-for-airflow
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              until curl -f http://airflow-webserver-service:8080/health; do
                echo "Waiting for Airflow..."
                sleep 5
              done
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/health-informatics-uon/carrot/frontend:{{ .Values.image.tag | default .Values.global.appVersion }}"
          imagePullPolicy: IfNotPresent
          command: 
            - node
            - server.js
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "frontend.fullname" . }}-config
            - secretRef:
                name: {{ include "frontend.fullname" . }}-secrets
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      