apiVersion: v2
name: carrot-mapper-k8s
description: An umbrella chart for deploying the entire Carrot Mapper stack
version: 0.1.0
appVersion: "1.0"
type: application
dependencies:
  - name: minio
    version: "17.0.9"
    repository: "https://charts.bitnami.com/bitnami"
  - name: omop-lite
    version: "*"
    repository: "file://omop-lite"
  - name: postgresql
    version: "16.7.15"
    repository: "https://charts.bitnami.com/bitnami"
  - name: api
    version: "*"
    repository: "file://api"
  - name: airflow
    version: "*"
    repository: "file://airflow"
  - name: frontend
    version: "*"
    repository: "file://frontend"
