apiVersion: v2
name: carrot-mapper
description: An umbrella chart for deploying the entire Carrot Mapper stack
version: 0.1.0
#  Shouldn't use this value. Use global.appVersion in values.yaml instead.
appVersion: "1.0"
type: application
dependencies:
  # External dependencies in the order they are deployed
  - name: minio
    version: "17.0.9"
    repository: "https://charts.bitnami.com/bitnami"
  - name: postgresql
    version: "16.7.15"
    repository: "https://charts.bitnami.com/bitnami"
  - name: omop-lite
    version: "*"
    repository: "file://omop-lite"
  - name: api
    version: "*"
    repository: "file://api"
  - name: airflow
    version: "*"
    repository: "file://airflow"
  - name: frontend
    version: "*"
    repository: "file://frontend"
